name: zoran.io

environment:
  sdk: '>=2.1.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_router: ^2.0.0-alpha+21
  angular_forms: ^2.0.0
  json_annotation: ^2.0.0
  yaml: ^2.1.15
  markdown: ^2.0.2

dev_dependencies:
  json_serializable: ^2.0.1
  build_web_compilers: ^0.4.2
  build_runner: ^1.1.2
  angular_test: ^2.2.0
  build_test: ^0.10.2
  test: ^1.5.1+1
  pageloader: ^3.0.0
  mockito: ^3.0.0-beta+1