name: sheets_dashboard

environment:
  sdk: '>=2.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_router: ^2.0.0-alpha+19
  angular_forms: ^2.0.0
  json_annotation: ^1.1.0
  markdown: ^2.0.2

dev_dependencies:
  json_serializable: ^1.1.0
  #angular_test: ^2.0.0-alpha+9
  build_runner: ^0.10.1
  #build_test: ^0.10.2
  build_web_compilers: ^0.4.2
  #test: ^1.0.0



