spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 2807563e28e21e5e1494
            client-secret: 8f81db99cb88a5f37c40a76589a269ff1b4b7a92
            scope: repo
            model_git_url: https://github.com/zoran-core/zoran-models.git