application:
  config:
    security:
      enabled: true
    storage:
      path: models
      local: local
    generator:
      defaultLicense: mit
spring:
  profiles:
    include:
    - github
    - data
    - initializr
    - pipeline
  application:
    name: zoran.io
  thymeleaf:
    enabled: false
eureka:
  client:
    register-with-eureka: false
    enabled: false