# branches:
#   only:
#     - develop

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install: 
        - cd ./zoran-core
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn test -P dev
    # - language: dart
    #   dart: stable
    #   before_install: 
    #     - cd ./zoran-ui
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      - language: dart 
        dart: 
          - dev
        sudo: required
        addons: 
          chrome: stable
        jobs:
          - stage: build
            script: 
              - pub run build_runner build
          - stage: copy
            script:
  - cd ..
  - cp ./zoran-ui/build/packages/sheets_dashboard ./zoran-core/target/classes/static
  - cd ./zoran-core
  - mvn install